### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by sravanmedarapu**
-  Updated gradle version 

- added` BySelector` attribute to `AndroidElement`

- enabled multi-window search to `getWindowRoots`

- Refactored `setAttribute`

### CODE REVIEW

**Comment by sravanmedarapu** [comment]
@imurchie, Can you review this PR when you get time.

**Comment by imurchie** [comment]
This looks fine to me. The only potential confusion I see is that the distinction between `BySelector` and `By` is non-obvious.

**Comment by sravanmedarapu** [comment]
[`BySelector`](https://developer.android.com/reference/android/support/test/uiautomator/BySelector.html) is from Google UIAutomator2 API used to find [UiObject2](https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#findObject) and By is maintained for internal purpose. 

In the current context storing `By` property in UiObjectElement & UiObject2Element for referring and cross checking.

**Comment by imurchie** [comment]
Understood. I just meant that coming to `By`, outside the context of this PR, it is unclear what it is and what distinguishes it from `BySelector`, particularly when they are next to each other.

**Comment by sravanmedarapu** [comment]
Will add comments in `By` class and where ever required would be helpful for better understanding.

In addition above, `By` is maintained to specify all supported possibilities for finding element/s in appium uiautomator2 driver.

**Pull request merged**
