### PR TITLE
Added NetworkConnection to suport set WIFI STATE

### PR DESCRIPTION
**Pull request by sravanmedarapu**
#https://github.com/appium/appium/issues/6615

cc: @jlipps, @imurchie

### CODE REVIEW

**Comment by jlipps** [comment]
code LGTM, looks like an element not found exception in the build, though?

**Comment by sravanmedarapu** [comment]
Yeah CI issue, Locally passed.

**Comment by jlipps** [comment]
@sravanmedarapu alright, you're good to merge and publish at will then.

**Comment by sravanmedarapu** [comment]
Sure @jlipps.

**Pull request merged**
