### PR TITLE
feat: Only include the actually queried attributes into the source xml

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
https://github.com/appium/appium-uiautomator2-server/issues/358#issuecomment-643531422

### CODE REVIEW

**Comment by sshock** [comment]
Will test on Monday...

**Comment by sshock** [comment]
Initial testing looks pretty good.

time (seconds) | uiautomator2 version
-- | --
56, 75, 55, 66 | * version 4.5.5
56, 56, 57, 55 | * master (version 4.8.3)
52, 50, 54 | * xml_attr branch (this MR)

I will plan on doing some more testing with more job types tomorrow.

**Comment by sshock** [comment]
Here are some more test results with various types of jobs we do.

uiaut2 version | Job A | Job B | Job C | Job D | Job E
-- | -- | -- | -- | -- | --
4.5.5 | 32,28,32 | 68,61,61 | 64,50,55 | 67,62,57 | 58,58,52
4.8.3 | 32,29,29 | 80,68,59 | 52,53,52 | 58,59,64 | 59,59,58
xml_attr branch | 31,31,27 | 58,52,56 | 57,51,52 | 66,58,57 | 68,51,51

I think it is safe to say this change does help a bit, with Job type B at least.  So it seems like a good change to me that can be merged.

The bad news is, this change alone doesn't seem to fully solve #358.  All of the job types (including Job B) are still noticeably slower than they were in Appium 1.9.1 (uiautomator2-server 1.18.0), as seen in the table at the top of that issue.

**Comment by mykola-mokhnach** [comment]
Thanks for checking this. Many things were changed since that version. Also, I would say it makes sense to sacrifice speed to correctness. @sshock feel free to share your further observations on that. We would be happy to help with what we can.

**Pull request merged**
