### PR TITLE
add Page Views

### PR DESCRIPTION
**Pull request by xdvrx1**
When we add this service, it will count every hit of this repo. And this will guide us more about the visitors each day and will indicate the total views. For me, this is very helpful both for us and for those will view this repo seeing this page views. If there is the website built from this repo, it can be simply added there too.

Screenshot (1705)

### CODE REVIEW

**Comment by xdvrx1** [comment]
I'll read the agreement. I may or may not sign.

**Comment by KazuCocoa** [comment]
Thanks!
We'll wait for the CLA

**Review by mykola-mokhnach — CHANGES_REQUESTED** [review]
I don't like the idea of having additional tracking (and don't like the idea of tracking in general). Currently it is fine to have the statistics that GitHub itself provides

**Comment by xdvrx1** [comment]
Yup, that was the answer when I was not satisfied by the GitHub Traffic. This one is a simple counter for every page hit. The most important one is, it's displayed on your page or repo README file, so that others will know also the visitors per day and the total count. It does not fetch data from either Google Analytics or GitHub Traffic.

You can check out the service too if there is doubt,

<https://hits.seeyoufarm.com/>

the development is in GitHub too:

<https://github.com/gjbae1212/hit-counter>

**Comment by mykola-mokhnach** [comment]
Sorry, but we have decided to not merge such PRs

**Pull request closed without merging**
