### PR TITLE
add index attribute on buildDomNode method

### PR DESCRIPTION
**Pull request by jjangah**
I was trying to find element by xpath with index attribute, but it seems like not implemented yet.
Is it just bug or other reasons that not implemented yet?

### CODE REVIEW

**Comment by sravanmedarapu** [comment]
Can you try to add a test for this, also please sign Licence Agreement.

**Comment by jjangah** [comment]
OK, I signed CLA and added test case.

**Comment by jjangah** [comment]
Sorry for messy commit :( 
it was my first fork and didn't know how to do.

**Comment by sravanmedarapu** [comment]
Nop, Can you please squash the commits in to a single commit.

**Comment by jjangah** [comment]
I think I messed up my git :(
Can I do re-fork and re-pull request?

**Comment by sravanmedarapu** [comment]
Sure.

**Pull request closed without merging**
