### PR TITLE
Bump uiautomator to 2.3.0-alpha01

### PR DESCRIPTION
**Pull request by ikalinin1**
The update is related to #490  and https://issuetracker.google.com/issues/176710836

### CODE REVIEW

**Comment by ikalinin1** [comment]
@mykola-mokhnach  Hello, could you please take a look.

**Comment by ikalinin1** [comment]
@mykola-mokhnach  @KazuCocoa  could you please take a look?

**Comment by KazuCocoa** [comment]
Based on https://github.com/appium/appium-uiautomator2-server/issues/490, we'd like to wait for the lib to be beta (at least) or stable release (ideally)

**Comment by KazuCocoa** [comment]
Note: alpha2 since 2023 01 11

**Comment by KazuCocoa** [comment]
Let me close now to wait for the stable release

**Pull request closed without merging**
